baseurl = "https://emc.phd/"
languageCode = "en-us"
theme = "re-terminal"
pagination.pagerSize = 5

[params]
  mainSections = []
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  readingTime = false

[languages]
  [languages.en.params]
    title = "Em Coombes"
    subtitle = "feminist sociologist researching networked movements"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "emc.phd"
      logoHomeLink = "/"

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[languages.en.menu.main]]
    identifier = "dissertation"
    name = "Dissertation"
    url = "/dissertation"
  [[languages.en.menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/uploads/cv.pdf"
